#+OPTIONS: toc:nil
#+TITLE: Política comparada III, primavera 2018
#+SUBTITLE: Trabajo parcial
#+AUTHOR: Eric Magar

El objetivo es buscar evidencia de coordinación electoral (o su ausencia) en elecciones municipales del país. 

Visite el repositorio siguiente: [[https://github.com/emagar/elecReturns/blob/master/data/aymu1985-present.coalAgg.csv]] y obtenga una copia de los datos. Se trata de los resultados de elecciones municipales desde 1985 (faltan las más recientes), encontrará la descripción del contenido en [[https://github.com/emagar/elecReturns/]]. 

Excluya observaciones anteriores a 2000. Plantee un diseño de investigación para detectar evidencia de coordinación o descoordinación electoral, tanto a nivel de élite como de masas. Sugiero que seleccione una muestra y no todos los municipios/años. Explore los datos para detectar patrones que ayuden a seleccionar un estado, o un grupo de estados, o un periodo.

Describa su diseño de investigación, las hipótesis que pone a prueba y reporte sus hallazgos de forma clara y distinta, sin rollo. 

La fecha de entrega será el *jueves 22 de marzo* en clase.
